import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Hero from "./Components/Hero";
import Frame from "./Components/Frame";
import WhyChoose from "./Components/WhyChoose";
import SmartResume from "./Components/SmartResume";
import FastJob from "./Components/FastJob";
import CareerMonitor from "./Components/CareerMonitor";
import Preview from "./Components/Preview";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job Mantic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="max-w-5xl mx-auto px-4">
          {/* Navigation Bar */}
          <Navbar />
          {children}
          <Hero></Hero>
          <Frame></Frame>
          <WhyChoose></WhyChoose>
          <SmartResume></SmartResume>
          <FastJob></FastJob>
          <CareerMonitor></CareerMonitor>
          <Preview></Preview>
        </div>
      </body>
    </html>
  );
}
